apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: tekton-pipelines
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Howdy Dev(Sec)Ops bootcamp :)"
